apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viewer
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["pods", "secrets", "configmaps", "deployments", "services"]
  verbs: ["get", "watch", "list"]